### ISSUE TITLE
Teensy 4.0?

### ISSUE THREAD

**Issue by GeoffreyPlitt** [Doom64/fluidsynth-lite#8]
Would this work on the latest Teensy?

**Comment by dotfloat** [comment]
Doesn't hurt to try, but I wouldn't bet on it. [The original project's](https://github.com/FluidSynth/fluidsynth) goal seems to be to create a synthesiser for use in music production. This repository differs little and is only meant to power some games on machines where we can afford to waste resources needlessly. That is, it wasn't developed with low-resources real-time applications in mind.
